export interface Article {
  id: string;
  title: string;
  category: string;
  content: string;
  wordCount: number;
}

export const articles: Article[] = [
  {
    id: "tech-ai-future",
    title: "The Future of Artificial Intelligence",
    category: "Technology",
    content: "Artificial intelligence has evolved from science fiction to an integral part of our daily lives. From the smartphones in our pockets to the recommendation algorithms that suggest what we watch next, AI systems are becoming increasingly sophisticated and ubiquitous. Machine learning models can now generate human-like text, create stunning artwork, and even write code. The rapid advancement in natural language processing has led to chatbots that can engage in meaningful conversations, while computer vision systems can identify objects and faces with remarkable accuracy. However, this technological revolution brings both opportunities and challenges. On one hand, AI promises to revolutionize healthcare by enabling early disease detection, personalized treatment plans, and drug discovery acceleration. In education, adaptive learning systems can provide customized instruction tailored to individual student needs. The automotive industry is racing toward fully autonomous vehicles that could significantly reduce traffic accidents and improve transportation efficiency. On the other hand, concerns about job displacement, privacy, and algorithmic bias continue to grow. As AI systems become more powerful, questions about their decision-making processes and potential for misuse become increasingly important. The development of artificial general intelligence, a system that could match or exceed human cognitive abilities across all domains, remains a topic of intense debate among researchers and ethicists. Some argue that such systems could solve humanity's greatest challenges, from climate change to poverty, while others warn of existential risks. As we navigate this transformative period, it becomes crucial to develop AI responsibly, ensuring that these powerful technologies benefit all of humanity while minimizing potential harm.",
    wordCount: 246
  },
  {
    id: "nature-climate-change",
    title: "Climate Change and Environmental Conservation",
    category: "Environment",
    content: "Climate change represents one of the most pressing challenges of our time, fundamentally altering weather patterns, ecosystems, and human societies worldwide. Rising global temperatures, primarily driven by greenhouse gas emissions from human activities, are causing ice caps to melt, sea levels to rise, and extreme weather events to become more frequent and severe. The evidence is overwhelming: record-breaking heatwaves, devastating wildfires, prolonged droughts, and intense hurricanes are becoming the new normal. These changes don't just affect the environment; they have profound implications for agriculture, water resources, public health, and economic stability. Small island nations face the existential threat of complete submersion, while coastal cities worldwide must adapt to rising seas. Agricultural regions are experiencing shifting growing seasons and changing precipitation patterns, affecting food security for millions. The scientific consensus is clear: immediate and sustained action is required to limit global warming to manageable levels. This involves a comprehensive transformation of our energy systems, moving away from fossil fuels toward renewable sources like solar, wind, and hydroelectric power. Energy efficiency improvements in buildings, transportation electrification, and industrial process optimization are all crucial components of climate mitigation strategies. However, technological solutions alone are insufficient. Behavioral changes, policy reforms, and international cooperation are equally important. Individuals can contribute by reducing energy consumption, choosing sustainable transportation options, and supporting environmentally responsible businesses. Governments must implement carbon pricing mechanisms, invest in clean energy infrastructure, and enforce environmental regulations. The transition to a sustainable future requires unprecedented global coordination and commitment from all sectors of society.",
    wordCount: 264
  },
  {
    id: "space-exploration",
    title: "The New Era of Space Exploration",
    category: "Science",
    content: "Space exploration has entered an exciting new chapter, characterized by renewed international cooperation, private sector involvement, and ambitious missions to destinations once considered unreachable. The successful landing of NASA's Perseverance rover on Mars represents a significant milestone in our quest to understand the Red Planet and search for signs of ancient microbial life. Meanwhile, the James Webb Space Telescope is revolutionizing our understanding of the universe, capturing images of distant galaxies and providing insights into the formation of stars and planetary systems. Commercial space companies have transformed the industry landscape, making space access more affordable and frequent. SpaceX's reusable rocket technology has dramatically reduced launch costs, enabling more frequent missions and opening opportunities for smaller organizations and countries to participate in space activities. The International Space Station continues to serve as a crucial platform for scientific research, international cooperation, and preparation for future deep space missions. Plans for returning humans to the Moon through NASA's Artemis program aim to establish a sustainable lunar presence that could serve as a stepping stone for eventual Mars exploration. These missions will require unprecedented technological innovations, from advanced life support systems to radiation shielding and in-situ resource utilization capabilities. The potential benefits of space exploration extend far beyond scientific knowledge. Satellite technology enables global communications, weather monitoring, and navigation systems that are integral to modern life. Space-based research contributes to medical advances, materials science breakthroughs, and environmental monitoring capabilities. As we look toward the future, space exploration promises to inspire new generations of scientists and engineers while potentially providing solutions to challenges facing humanity on Earth.",
    wordCount: 270
  },
  {
    id: "digital-education",
    title: "Digital Transformation in Education",
    category: "Education",
    content: "The digital transformation of education has accelerated rapidly, fundamentally changing how students learn and teachers instruct. Online learning platforms, virtual classrooms, and educational apps have made knowledge more accessible than ever before. Students can now access world-class courses from prestigious universities, learn new skills through interactive platforms, and collaborate with peers across the globe. Adaptive learning technologies use artificial intelligence to personalize educational experiences, adjusting content difficulty and pacing based on individual student progress and learning styles. This personalized approach helps ensure that no student is left behind while challenging advanced learners appropriately. Virtual and augmented reality technologies are creating immersive educational experiences, allowing students to explore ancient civilizations, conduct virtual science experiments, and visualize complex concepts in three-dimensional space. Digital tools have also transformed assessment methods, enabling real-time feedback, automated grading, and comprehensive learning analytics that help educators identify areas where students need additional support. However, the digital divide remains a significant challenge, as not all students have equal access to technology and high-speed internet connectivity. This disparity can exacerbate existing educational inequalities and limit opportunities for disadvantaged students. Additionally, concerns about screen time, digital addiction, and the loss of face-to-face social interactions have prompted discussions about finding the right balance between digital and traditional learning methods. Teachers have had to rapidly adapt their instructional strategies, developing new skills in technology integration and online pedagogy. Professional development programs have become essential to help educators effectively leverage digital tools while maintaining engaging and meaningful learning experiences. As educational technology continues to evolve, the focus must remain on enhancing learning outcomes and ensuring that all students have the opportunity to succeed in an increasingly digital world.",
    wordCount: 284
  },
  {
    id: "renewable-energy",
    title: "The Renewable Energy Revolution",
    category: "Technology",
    content: "The global transition to renewable energy sources is accelerating at an unprecedented pace, driven by technological advances, economic incentives, and growing environmental awareness. Solar and wind power have become the cheapest sources of electricity in many regions, making renewable energy not just an environmental imperative but also an economic advantage. Photovoltaic technology has improved dramatically, with solar panel efficiency increasing while costs have plummeted by over eighty percent in the past decade. Wind turbines have grown larger and more efficient, capable of generating power even in low-wind conditions through advanced blade designs and smart control systems. Energy storage technologies, particularly battery systems, are solving the intermittency challenge associated with renewable sources. Large-scale battery installations can store excess energy generated during peak production periods and release it when demand is high or generation is low. Pumped hydro storage, compressed air energy storage, and emerging technologies like hydrogen fuel cells provide additional options for long-term energy storage and grid stabilization. Smart grid technologies enable better integration of renewable sources by predicting energy demand, optimizing distribution, and automatically balancing supply and demand across the electrical grid. Electric vehicles are becoming both consumers and contributors to the energy ecosystem, with vehicle-to-grid technology allowing cars to store renewable energy and feed it back into the grid when needed. Government policies and international agreements are accelerating the renewable transition through subsidies, tax incentives, and carbon pricing mechanisms. Many countries have committed to achieving net-zero emissions by mid-century, requiring massive investments in clean energy infrastructure. The renewable energy sector has become a significant source of employment, creating millions of jobs in manufacturing, installation, maintenance, and research and development. As costs continue to decrease and efficiency improves, renewable energy is poised to become the dominant global energy source.",
    wordCount: 295
  },
  {
    id: "mental-health-awareness",
    title: "Mental Health in the Modern World",
    category: "Health",
    content: "Mental health awareness has gained unprecedented attention in recent years, breaking down longstanding stigmas and encouraging open conversations about psychological wellbeing. The modern world presents unique challenges to mental health, from social media pressure and information overload to work-related stress and social isolation. Anxiety and depression rates have increased significantly, particularly among young people who have grown up in an era of constant connectivity and comparison. The COVID-19 pandemic further highlighted the importance of mental health support, as lockdowns and social distancing measures led to increased feelings of loneliness, uncertainty, and psychological distress. However, this crisis also accelerated the adoption of teletherapy and digital mental health tools, making professional support more accessible to those who previously faced barriers to treatment. Mental health apps, online therapy platforms, and virtual support groups have democratized access to mental health resources, allowing individuals to seek help from the comfort and privacy of their homes. Workplace mental health has become a priority for employers who recognize that employee wellbeing directly impacts productivity, creativity, and retention. Companies are implementing comprehensive mental health programs, providing stress management resources, and creating supportive work environments that prioritize work-life balance. Educational institutions are also recognizing their role in promoting mental health, integrating social-emotional learning into curricula and providing counseling services for students. The understanding of mental health has evolved to encompass a holistic view of wellbeing that includes physical health, social connections, purpose, and resilience. Preventive approaches focus on building coping skills, fostering supportive relationships, and creating environments that promote psychological safety. As awareness continues to grow, the focus is shifting from merely treating mental illness to promoting mental wellness and creating communities that support the psychological flourishing of all individuals.",
    wordCount: 289
  }
];

export function getArticleById(id: string): Article | undefined {
  return articles.find(article => article.id === id);
}

export function getArticlesByCategory(category: string): Article[] {
  return articles.filter(article => article.category === category);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(articles.map(article => article.category)));
}